services:

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
    container_name: backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/password-manager
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: frontend
    restart: always
    ports:
      - "80:80"   # production port mapping
      - "443:443"
    depends_on:
      - backend
    volumes:
    - /etc/letsencrypt/live/a-tran.dev:/etc/letsencrypt/live/a-tran.dev:ro
    - /etc/letsencrypt/archive/a-tran.dev:/etc/letsencrypt/archive/a-tran.dev:ro
    - /var/lib/letsencrypt:/var/lib/letsencrypt:ro

volumes:
  mongo_data: